### ISSUE TITLE
OptionAgent.run_agent doesn't work if environment inherits from Environment and not BaseEnvironment

### ISSUE THREAD

**Issue by akshilll** [Ueva/BaRL-SimpleOptions#9]
This is because of the fact that the signatures for get_available_options are different for each class, one expects an extra argument (state) and the other does not. 

Simple fix is to just change the signature of the method in environment to expect a state!

**Comment by Ueva** [comment]
Thanks for reporting, completely missed this. Fixed in 9be6ebd.
